export const presets = [
    {
        name: "light",
        icon: "far fa-moon",
        primary: "#6200EE",
        primaryVariant: "#B080F6",
        secondary: "#02A494",
        secondaryVariant: "#018786",
        background: "#FFFFFF",
        surface: "#FAFAFA",
        error: "#B00020",
        onPrimaryHigh: "#FFFFFFDE",
        onPrimaryMedium: "#FFFFFF99",
        onPrimaryDisabled: "#FFFFFF61",
        onSecondaryHigh: "#000000DE",
        onSecondaryMedium: "#00000099",
        onSecondaryDisabled: "#00000061",
        onBackgroundHigh: "#000000DE",
        onBackgroundMedium: "#00000099",
        onBackgroundDisabled: "#00000061",
        onSurfaceHigh: "#000000DE",
        onSurfaceMedium: "#00000099",
        onSurfaceDisabled: "#00000061",
        onError: "#FFFFFF",
    },
    {
        name: "dark",
        icon: "far fa-sun",
        primary: "#BB86FC",
        primaryVariant: "#7A57A4",
        secondary: "#03DAC6",
        secondaryVariant: "#03DAC6",
        background: "#121212",
        surface: "#191919",
        error: "#CF6679",
        onPrimaryHigh: "#000000DE",
        onPrimaryMedium: "#00000099",
        onPrimaryDisabled: "#00000061",
        onSecondaryHigh: "#FFFFFFDE",
        onSecondaryMedium: "#FFFFFF99",
        onSecondaryDisabled: "#FFFFFF61",
        onBackgroundHigh: "#FFFFFFDE",
        onBackgroundMedium: "#FFFFFF99",
        onBackgroundDisabled: "#FFFFFF61",
        onSurfaceHigh: "#FFFFFFDE",
        onSurfaceMedium: "#FFFFFF99",
        onSurfaceDisabled: "#FFFFFF61",
        onError: "#FFFFFF",
    },
]